name: yumm_ai
description: "A Generative AI meal recommendation project"


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_lucide: ^1.7.0
  flutter_svg: ^2.2.3
  readmore: ^3.0.0
  cached_network_image: ^3.4.1
  go_router: ^17.0.0
  camera: ^0.11.3
  gal: ^2.3.2
  flutter_native_splash: ^2.4.7
  hive_generator: ^2.0.1
  flutter_gemini: ^3.0.0
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.1.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  hive: ^2.2.3
  uuid: ^4.5.2
  freezed_annotation: ^3.1.0
  workmanager: ^0.9.0+3
  jwt_decoder: ^2.0.1
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.6
  json_serializable: ^6.8.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 


flutter:

  uses-material-design: true

  
  assets:
    - assets/kitchen_tools.json
    - assets/ingridents.json
    - assets/images/
    - assets/svgs/
    - .env

  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets\fonts\poppins\light.ttf
          weight: 100
        - asset: assets\fonts\poppins\regular.ttf
          weight: 200
        - asset: assets\fonts\poppins\medium.ttf
          weight: 300
        - asset: assets\fonts\poppins\semi_bold.ttf
          weight: 400
        - asset: assets\fonts\poppins\bold.ttf
          weight: 500
        - asset: assets\fonts\poppins\extra_bold.ttf
          weight: 600

flutter_native_splash:
  
  color: "
  
  
  image: assets/images/text_logo.png
  
  
  color_dark: "
  image_dark: assets/images/text_logo.png
  
  
  android_12:
    image: assets/images/text_logo.png
    color: "
    image_dark: assets/images/text_logo.png
    color_dark: "